name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
jobs:
  build-angular:
    name: Build front (Angular app)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node Version ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install and npm run build (dev)
        run: |
          cd client
          npm install
          npm run build