spring:
  application:
    name: okastock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 2fae0752b9ca693115d51e06bd8976e4c4f8e6cca9d5288ef30dd89408fe998aa83728a18bf27fe37c8b89955b5c0e858440fc211578b737115107ffabc0122e