name: CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
        java_version: ['17']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
      - name: Build back with Maven
        run: |
            cd api
            mvn clean install
      - name: Set up Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Build front with npm
        run: |
          cd client
          npm install
          npm run build
          - uses: actions/checkout@master
      - if: success()
        name: Send success notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: COOL ! La compilation a été un succès.
      - if: failure()
        name: Send failure notification to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: AY ! Une erreur est survenue pendant la compilation.      
